paths:
  /api/comments/{id}:
    get:
      tags:
        - Comments
      summary: Return comment by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleCommentJsonApiResponse'
        '404':
          description: Not Found

  /api/comments/{commentId}:
    put:
      tags:
        - Comments
      summary: Update existing comment by id with InputModel
      security:
        - bearer: []
      parameters:
        - name: commentId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputModels.UpdateCommentInputModel'
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
    delete:
      tags:
        - Comments
      summary: Delete comment specified by id
      security:
        - bearer: []
      parameters:
        - name: commentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '404':
          description: Not Found

  /api/comments/{commentId}/like-status:
    put:
      tags:
        - Comments
      summary: Make like/unlike/dislike/undislike operation
      security:
        - bearer: []
      parameters:
        - name: commentId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputModels.UpdateLikeStatusInputModel'
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
