tags:
  - name: Auth
    description: Authentication and authorization
  - name: Users
    description: User management (admin)
  - name: Blogs
    description: Blog management
  - name: Posts
    description: Post management
  - name: Comments
    description: Comment management
  - name: Videos
    description: Video management
  - name: SecurityDevices
    description: Security devices management
  - name: Testing
    description: Testing utilities

components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
    refreshToken:
      type: apiKey
      in: cookie
      name: refreshToken
      description: JWT refreshToken inside cookie. Must be correct, and must not expire
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Enter JWT Bearer token **only**

  responses:
    ValidationError:
      description: If the inputModel has incorrect values
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponseBody'
    DomainError:
      description: Domain or business logic error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponseBody'

  schemas:
    Extension:
      type: object
      properties:
        key:
          type: string
        message:
          type: string
      required:
        - key
        - message

    DomainExceptionCode:
      description: |
        Domain error code (see `core/exceptions/domain-exception-code.ts`):
        0 — BadRequest, 1 — ValidationError, 2 — NotFound, 3 — Forbidden,
        4 — Unauthorized, 5 — InternalServerError, 6 — ConfirmationCodeExpired,
        7 — EmailNotConfirmed, 8 — PasswordRecoveryCodeExpired
      type: integer
      enum: [0, 1, 2, 3, 4, 5, 6, 7, 8]
      x-enum-varnames:
        - BadRequest
        - ValidationError
        - NotFound
        - Forbidden
        - Unauthorized
        - InternalServerError
        - ConfirmationCodeExpired
        - EmailNotConfirmed
        - PasswordRecoveryCodeExpired

    ErrorResponseBody:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        path:
          type: string
        message:
          type: string
        code:
          description: |
            Domain error code (see `core/exceptions/domain-exception-code.ts`):
            0 — BadRequest, 1 — ValidationError, 2 — NotFound, 3 — Forbidden,
            4 — Unauthorized, 5 — InternalServerError, 6 — ConfirmationCodeExpired,
            7 — EmailNotConfirmed, 8 — PasswordRecoveryCodeExpired
          type: integer
          enum: [0, 1, 2, 3, 4, 5, 6, 7, 8]
          x-enum-varnames:
            - BadRequest
            - ValidationError
            - NotFound
            - Forbidden
            - Unauthorized
            - InternalServerError
            - ConfirmationCodeExpired
            - EmailNotConfirmed
            - PasswordRecoveryCodeExpired
        extensions:
          type: array
          items:
            $ref: '#/components/schemas/Extension'
      required:
        - timestamp
        - path
        - message
        - code
        - extensions

    InputModels.SigninInputModel:
      description: Input model
      type: object
      properties:
        loginOrEmail:
          type: string
        password:
          type: string
      required:
        - loginOrEmail
        - password

    InputModels.SignupInputModel:
      description: Input model
      type: object
      properties:
        login:
          type: string
        email:
          type: string
        password:
          type: string
      required:
        - login
        - email
        - password

    InputModels.RegistrationConfirmInputModel:
      description: Input model
      type: object
      properties:
        code:
          type: string
      required:
        - code

    InputModels.ResendRegistrationInputModel:
      description: Input model
      type: object
      properties:
        email:
          type: string
      required:
        - email

    InputModels.RecoveryPasswordInputModel:
      description: Input model
      type: object
      properties:
        email:
          type: string
      required:
        - email

    InputModels.NewPasswordInputModel:
      description: Input model
      type: object
      properties:
        recoveryCode:
          type: string
        newPassword:
          type: string
      required:
        - recoveryCode
        - newPassword

    InputModels.CreateUserInputModel:
      description: Input model
      type: object
      properties:
        login:
          type: string
        password:
          type: string
        email:
          type: string
      required:
        - login
        - password
        - email

    InputModels.CreateBlogInputModel:
      description: Input model
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        websiteUrl:
          type: string
      required:
        - name
        - description
        - websiteUrl

    InputModels.UpdateBlogInputModel:
      description: Input model
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        websiteUrl:
          type: string
      required:
        - name
        - description
        - websiteUrl

    InputModels.CreatePostInBlogInputModel:
      description: Input model
      type: object
      properties:
        title:
          type: string
        shortDescription:
          type: string
        content:
          type: string
      required:
        - title
        - shortDescription
        - content

    InputModels.CreatePostInputModel:
      description: Input model
      type: object
      properties:
        title:
          type: string
        shortDescription:
          type: string
        content:
          type: string
        blogId:
          type: string
      required:
        - title
        - shortDescription
        - content
        - blogId

    InputModels.UpdatePostInputModel:
      description: Input model
      type: object
      properties:
        title:
          type: string
        shortDescription:
          type: string
        content:
          type: string
        blogId:
          type: string
      required:
        - title
        - shortDescription
        - content
        - blogId

    InputModels.CreateCommentInputModel:
      description: Input model
      type: object
      properties:
        content:
          type: string
      required:
        - content

    InputModels.UpdateCommentInputModel:
      description: Input model
      type: object
      properties:
        content:
          type: string
      required:
        - content

    InputModels.UpdateLikeStatusInputModel:
      description: Input model
      type: object
      properties:
        likeStatus:
          $ref: '#/components/schemas/LikeStatus'
      required:
        - likeStatus

    ViewModels.AccessTokenViewModel:
      description: View model
      type: object
      properties:
        accessToken:
          type: string
      required:
        - accessToken

    ViewModels.MeViewModel:
      description: View model
      type: object
      properties:
        userId:
          type: string
        login:
          type: string
        email:
          type: string
      required:
        - userId
        - login
        - email

    ViewModels.UserViewModel:
      description: View model
      type: object
      properties:
        login:
          type: string
        email:
          type: string
        createdAt:
          type: string
      required:
        - login
        - email
        - createdAt

    ViewModels.BlogViewModel:
      description: View model
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        websiteUrl:
          type: string
        isMembership:
          type: boolean
        createdAt:
          type: string
      required:
        - name
        - description
        - websiteUrl
        - isMembership
        - createdAt

    ViewModels.SecurityDeviceViewModel:
      description: View model
      type: object
      properties:
        deviceId:
          type: string
        ip:
          type: string
        title:
          type: string
        lastActiveDate:
          type: string
      required:
        - deviceId
        - ip
        - title
        - lastActiveDate

    SortDirections:
      description: Sort directions
      type: string
      enum: [asc, desc]

    SortUsersBy:
      description: Sort directions
      type: string
      enum: [login, email, createdAt]

    SortBlogsBy:
      description: Sort directions
      type: string
      enum: [name, description, websiteUrl, createdAt]

    SortPostsBy:
      description: Sort directions
      type: string
      enum: [title, shortDescription, content, blogName, createdAt]

    SortPostCommentsBy:
      description: Sort directions
      type: string
      enum: [content, createdAt]

    PaginationMeta:
      type: object
      properties:
        page:
          type: integer
        pageSize:
          type: integer
        pageCount:
          type: integer
        totalCount:
          type: integer
      required:
        - page
        - pageSize
        - pageCount
        - totalCount

    LikeStatus:
      type: string
      enum: [None, Like, Dislike]

    CommentatorInfo:
      type: object
      properties:
        userId:
          type: string
        userLogin:
          type: string
      required:
        - userId
        - userLogin

    LikesInfo:
      type: object
      properties:
        likesCount:
          type: integer
        dislikesCount:
          type: integer
        myStatus:
          $ref: '#/components/schemas/LikeStatus'
      required:
        - likesCount
        - dislikesCount
        - myStatus

    NewestLike:
      type: object
      properties:
        addedAt:
          type: string
        userId:
          type: string
        login:
          type: string
      required:
        - addedAt
        - userId
        - login

    ExtendedLikesInfo:
      type: object
      properties:
        likesCount:
          type: integer
        dislikesCount:
          type: integer
        myStatus:
          $ref: '#/components/schemas/LikeStatus'
        newestLikes:
          type: array
          items:
            $ref: '#/components/schemas/NewestLike'
      required:
        - likesCount
        - dislikesCount
        - myStatus
        - newestLikes

    UserAttributes:
      type: object
      properties:
        login:
          type: string
        email:
          type: string
        createdAt:
          type: string
      required:
        - login
        - email
        - createdAt

    BlogAttributes:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        websiteUrl:
          type: string
        isMembership:
          type: boolean
        createdAt:
          type: string
      required:
        - name
        - description
        - websiteUrl
        - isMembership
        - createdAt

    CommentAttributes:
      type: object
      properties:
        content:
          type: string
        commentatorInfo:
          $ref: '#/components/schemas/CommentatorInfo'
        createdAt:
          type: string
        likesInfo:
          $ref: '#/components/schemas/LikesInfo'
      required:
        - content
        - commentatorInfo
        - createdAt
        - likesInfo

    PostAttributes:
      type: object
      properties:
        title:
          type: string
        shortDescription:
          type: string
        content:
          type: string
        blogId:
          type: string
        blogName:
          type: string
        createdAt:
          type: string
        extendedLikesInfo:
          $ref: '#/components/schemas/ExtendedLikesInfo'
      required:
        - title
        - shortDescription
        - content
        - blogId
        - blogName
        - createdAt
        - extendedLikesInfo

    UserJsonApiResource:
      type: object
      properties:
        type:
          type: string
          enum: [users]
        id:
          type: string
        attributes:
          $ref: '#/components/schemas/UserAttributes'
      required:
        - type
        - id
        - attributes

    BlogJsonApiResource:
      type: object
      properties:
        type:
          type: string
          enum: [blogs]
        id:
          type: string
        attributes:
          $ref: '#/components/schemas/BlogAttributes'
      required:
        - type
        - id
        - attributes

    CommentJsonApiResource:
      type: object
      properties:
        type:
          type: string
          enum: [comments]
        id:
          type: string
        attributes:
          $ref: '#/components/schemas/CommentAttributes'
      required:
        - type
        - id
        - attributes

    PostJsonApiResource:
      type: object
      properties:
        type:
          type: string
          enum: [posts]
        id:
          type: string
        attributes:
          $ref: '#/components/schemas/PostAttributes'
      required:
        - type
        - id
        - attributes

    JsonApiResource:
      type: object
      properties:
        type:
          type: string
          enum: [posts, blogs, users, comments]
        id:
          type: string
        attributes:
          type: object
      required:
        - type
        - id
        - attributes

    SingleJsonApiResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/JsonApiResource'
      required:
        - data

    SingleUserJsonApiResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/UserJsonApiResource'
      required:
        - data

    SingleBlogJsonApiResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/BlogJsonApiResource'
      required:
        - data

    SingleCommentJsonApiResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/CommentJsonApiResource'
      required:
        - data

    SinglePostJsonApiResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/PostJsonApiResource'
      required:
        - data

    PaginatedJsonApiResponse:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/PaginationMeta'
        data:
          type: array
          items:
            $ref: '#/components/schemas/JsonApiResource'
      required:
        - meta
        - data

    PaginatedUserJsonApiResponse:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/PaginationMeta'
        data:
          type: array
          items:
            $ref: '#/components/schemas/UserJsonApiResource'
      required:
        - meta
        - data

    PaginatedBlogJsonApiResponse:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/PaginationMeta'
        data:
          type: array
          items:
            $ref: '#/components/schemas/BlogJsonApiResource'
      required:
        - meta
        - data

    PaginatedCommentJsonApiResponse:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/PaginationMeta'
        data:
          type: array
          items:
            $ref: '#/components/schemas/CommentJsonApiResource'
      required:
        - meta
        - data

    PaginatedPostJsonApiResponse:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/PaginationMeta'
        data:
          type: array
          items:
            $ref: '#/components/schemas/PostJsonApiResource'
      required:
        - meta
        - data

    UpdateLikeStatusInput:
      type: object
      properties:
        likeStatus:
          $ref: '#/components/schemas/LikeStatus'
      required:
        - likeStatus
